routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CcpsCore\HomeController@index')->name('home');
Route::get('home', 'CcpsCore\HomeController@index');

Route::group(['prefix' => 'account'], function() {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');
});

// Routes from Modules
$ccpsModules = collect(config('ccps.modules'));
$adminModules = $ccpsModules->where('parent', 'admin')->where('use_custom_routes', false);

Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {
    Route::get('/', 'CcpsCore\AdminController@index')->name('admin');

    foreach(config('ccps.modules') as $name => $module) {
        if (!$module['use_custom_routes'] && $module['parent'] == 'admin') {
            require_once(base_path('vendor/' . $module['package'] . '/src/routes/' . $name . '.php'));
        }
    }
});

foreach(config('ccps.modules') as $name => $module) {
    if (!$module['use_custom_routes'] && empty($module['parent'])) {
        require_once(base_path('vendor/' . $module['package'] . '/src/routes/' . $name . '.php'));
    }
}

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');

Route::resource('widgets', 'WidgetsController');
Route::get('widgets/{widget}/audits', 'WidgetsController@audits')->name('widgets.audits');

Route::get('notify', function() {
    \Illuminate\Support\Facades\Notification::route(\Uncgits\Ccps\Channels\GoogleChatWebhookChannel::class, '')->notify(new \App\Notifications\SomethingBorked());
});

app/Widget.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
    use OwenIt\Auditing\Auditable as AuditableTrait;
    
class Widget extends Model implements AuditableContract
{
    use Sortable;
    use AuditableTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'widgets';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description'];

    public $sortable = ['id', 'created_at', 'updated_at', 'name', 'description'];

    
}

app/Http/Controllers/WidgetsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Widget;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use Uncgits\Ccps\Support\CcpsPaginator;

class WidgetsController extends Controller
{
    /**
     * Constructor
     *
     */

    public function __construct() {
        // Basic ACL middleware using Laratrust

        $this->middleware('permission:widgets.create')->only(['create', 'store']);
        $this->middleware('permission:widgets.read')->only(['index', 'show', 'audits']);
        $this->middleware('permission:widgets.update')->only(['edit', 'update']);
        $this->middleware('permission:widgets.delete')->only(['destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');

        if (!empty($keyword)) {
            $widgets = Widget::where('name', 'LIKE', "%$keyword%")
                ->orWhere('description', 'LIKE', "%$keyword%")
                ->sortable('id')->get();
        } else {
            $widgets = Widget::sortable('id')->get();
        }

        $widgets = new CcpsPaginator($widgets);

        return view('widgets.index', compact('widgets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('widgets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        
        $requestData = $request->all();
        
        

        Widget::create($requestData);

        return redirect('widgets')->with('flash_message', 'Widget added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $widget = Widget::findOrFail($id);

        return view('widgets.show', compact('widget'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $widget = Widget::findOrFail($id);

        return view('widgets.edit', compact('widget'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        
        $requestData = $request->all();
        
        

        $widget = Widget::findOrFail($id);
        $widget->update($requestData);

        return redirect('widgets')->with('flash_message', 'Widget updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Widget::destroy($id);

        return redirect('widgets')->with('flash_message', 'Widget deleted!');
    }

    public function audits(Widget $widget) {
        $widget->load('audits.user');
        $audits = $widget->audits->sortByDesc('created_at');
        return view('widgets.audits', compact(['widget', 'audits']));
    }
}

resources/views/widgets/audits.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Widget | Audits'
])

@section('content')
    <div class="row">
        <div class="col">
            <h1>Audits for Widget {{ $widget->id }}</h1>
            @include('partials.audit-table', ['audits' => $audits])
        </div>
    </div>
@endsection()

resources/views/widgets/create.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Widget | Create'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">Create New Widget</div>
                    <div class="card-body">
                        <a href="{{ route('widgets.index') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fas fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('widgets.store') }}" accept-charset="UTF-8" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('widgets.form')

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/widgets/edit.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Widget | Edit'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">Edit Widget #{{ $widget->id }}</div>
                    <div class="card-body">
                        <a href="{{ route('widgets.index') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fas fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('widgets.update', ['id' => $widget->id]) }}" accept-charset="UTF-8" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('widgets.form', ['submitButtonText' => 'Update'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/widgets/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    <label for="name" class="col control-label">{{ 'Name' }}</label>
    <div class="col">
        <input class="form-control" name="name" type="text" id="name" value="{{ $widget->name or ''}}" >

        {!! $errors->first('name', '<div class="invalid-feedback">:message</div>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
    <label for="description" class="col control-label">{{ 'Description' }}</label>
    <div class="col">
        <textarea class="form-control" rows="5" name="description" type="textarea" id="description" >{{ $widget->description or ''}}</textarea>
        {!! $errors->first('description', '<div class="invalid-feedback">:message</div>') !!}
    </div>
</div>


<div class="form-group">
    <div class="col">
        <input class="btn btn-primary" type="submit" value="{{ $submitButtonText or 'Create' }}">
    </div>
</div>

resources/views/widgets/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Widget | Index'
])

@section('content')
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header"><h5 class="mb-0">Widgets</h5></div>
                <div class="card-body row">
                    <div class="col">
                        @permission('widgets.create')
                        <a href="{{ route('widgets.create') }}" class="btn btn-success btn-sm" title="Add New Widget">
                            <i class="fas fa-plus" aria-hidden="true"></i> Add New
                        </a>
                        @endpermission
                    </div>

                    <div class="col3">
                        <form method="GET" action="{{ route('widgets.index') }}" accept-charset="UTF-8" role="search">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Search..." aria-label="Search" name="search" value="{{ request('search') }}">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-dark"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>


                    <br/>
                    <br/>
                    <div class="table-responsive">
                        {!! $widgets->header() !!}
                        <table class="table table-striped table-sm">
                            <thead>
                                <tr>
                                    <th scope="col">@sortablelink('id', '#')</th><th scope="col">@sortablelink('name', 'Name')</th><th scope="col">@sortablelink('description', 'Description')</th><th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($widgets as $item)
                                <tr>
                                    <th scope="row">{{ $item->id or $loop->iteration }}</th>
                                    <td>{{ $item->name }}</td><td>{{ $item->description }}</td>
                                    <td>
                                        @permission('widgets.read')
                                        <a href="{{ route('widgets.show',  ['id' => $item->id]) }}" title="View Widget"><button class="btn btn-info btn-sm"><i class="fas fa-eye" aria-hidden="true"></i> View</button></a>
                                        @endpermission

                                        @permission('widgets.update')
                                        <a href="{{ route('widgets.edit',  ['id' => $item->id]) }}" title="Edit Widget"><button class="btn btn-primary btn-sm"><i class="fas fa-edit" aria-hidden="true"></i> Edit</button></a>
                                        @endpermission

                                        @permission('widgets.delete')
                                        <form method="POST" action="{{ route('widgets.destroy', ['id' => $item->id]) }}" accept-charset="UTF-8" style="display:inline">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Widget" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fas fa-trash" aria-hidden="true"></i> Delete</button>
                                        </form>
                                        @endpermission
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="row justify-content-center">
                            {!! $widgets->appends(Request::except('page'))->render() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/widgets/show.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Widget | Show'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">Widget {{ $widget->id }}</div>
                    <div class="card-body">

                        <a href="{{ route('widgets.index') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fas fa-arrow-left" aria-hidden="true"></i> Back</button></a>

                        @permission('widgets.update')
                        <a href="{{ route('widgets.edit', ['id' => $widget->id]) }}" title="Edit Widget"><button class="btn btn-primary btn-sm"><i class="fas fa-edit" aria-hidden="true"></i> Edit</button></a>
                        @endpermission

                        @permission('widgets.delete')
                        <form method="POST" action="{{ route('widgets.destroy', ['id' => $widget->id]) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Widget" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fas fa-trash" aria-hidden="true"></i> Delete</button>
                        </form>
                        @endpermission

                        <a href="{{ route('widgets.audits', ['id' => $widget->id]) }}" title="Audits for Widget"><button class="btn btn-light btn-sm"><i class="fas fa-clock" aria-hidden="true"></i> Audits</button></a>

                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $widget->id }}</td>
                                    </tr>
                                    <tr><th> Name </th><td>{{ $widget->name }}</td></tr><tr><th> Description </th><td>{{ $widget->description }}</td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection